<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-B8GN0GEK" failures="0" tests="2" name="com.yolo.api.test.suite.invoker.PostAndUpdateTestCases" time="14.182" errors="1" timestamp="13 Nov 2021 07:51:51 GMT" skipped="0">
  <testcase classname="com.yolo.api.test.suite.invoker.PostAndUpdateTestCases" name="postCreateUser" time="4.795"/>
  <testcase classname="com.yolo.api.test.suite.invoker.PostAndUpdateTestCases" name="putUpdateUser" time="9.387">
    <error message="expected not same" type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError: expected not same
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failSame(Assert.java:271)
at junit.framework.Assert.assertNotSame(Assert.java:257)
at junit.framework.Assert.assertNotSame(Assert.java:264)
at com.yolo.api.test.suite.invoker.PostAndUpdateTestCases.putUpdateUser(PostAndUpdateTestCases.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- putUpdateUser -->
</testsuite> <!-- com.yolo.api.test.suite.invoker.PostAndUpdateTestCases -->
